The heatmap of Smashing Magazine Homepage
smcommits/Design-Teardown pull request #1
Opened 2020-10-01 15:51 UTC by smcommits

This is the project of HTML and CSS in which we created a heatmap the home page of https://www.smashingmagazine.com/. The aim was to highlight the attractive parts in dark colors and the unattractive parts in ligth color.

Feature:
- Used dark gray for focused parts and light gray for unfocused parts
- Used typogorpahy which is imported from google fonts.
- Contains hover effects replicated from original website
- Contains animations replicated from the original website

2020-10-01 16:41 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Amazing job so far, guys! 👍 
Your linters are green 🟢 
Clean code 💯 
Professional readme file 👏 
Very good use of float, grid and flex 🥇 
I am impressed! Keep it up, guys! 😃 

However, we need to make some changes before approving the project 💪 
Check my comments below 👇  make the changes and resubmit your project for a new code review

Good luck, team!

## Changes

- Kindly, remove the horizontal scrollbar
- There are some important heat points missing
   - 'Seriously, Ted?' on the upper right side of the main section
![Capture](https://user-images.githubusercontent.com/56809963/94838276-9ecd2180-0415-11eb-9e5e-ef017fa7f5d5.PNG)

   - In the latest post section, you only have 1 add in the second row, must be 2.
![Capture1](https://user-images.githubusercontent.com/56809963/94838302-a68cc600-0415-11eb-9fd5-29cf4946ddae.PNG)

   - The banner after that section should not be 100% width
![Capture2](https://user-images.githubusercontent.com/56809963/94838312-ad1b3d80-0415-11eb-975a-393d745a3ab0.PNG)

  [OPTIONAL]

- It is a good practice to use semantic HTML tags, call `footer` to the footer, `main` to the main section, `section` to each of the different sections in your page. It makes your code more readable and easy to follow.
- Improve your commit messages, make them explain what you did with a bit more of detail, so if you need to roll back you know where exactly made the changes.

2020-10-01 23:10 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__I must say, you've done an amazing job so far. However, there are some changes that are required to be fixed before this project can be approved. Please check my points below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] You should link the items in your footer section. Check my comments below for details.

![00:06:08](https://user-images.githubusercontent.com/26856491/94871909-182f3900-0443-11eb-8444-c52efcdac07e.png)

![00:07:29](https://user-images.githubusercontent.com/26856491/94871984-4876d780-0443-11eb-9b5d-eda5c0a353d7.png)


**[ COMMENTS ]**

- [ ] You should be careful of the way you use the `!important` rule in your CSS. If possible, try to avoid it. If not, using it in 1 or 2 places (like you did) is still okay. Overusing it can mess things up.


**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-10-01 23:10 UTC, teekaytech commented on index.html
> +      <li></li>
These footer items should be linked. For instance, we should have something like:
```
<ul>
 <li><a href=""></a></li>
 <li><a href=""></a></li>
</ul>
```
Although content is not important. Yet, this is a requirement.

2020-10-01 23:10 UTC, teekaytech commented on index.html
> +    </ul>
These should be linked too.

2020-10-02 16:19 UTC, javitocor approved these changes
# STATUS APPROVED 🥇 

Congratulations team, you have met all the requirements and your project is approved! 👏 
Do not forget to fill up the completion form and you can move into the next project ⏩ 

Good luck with it! 😃

2020-10-02 16:42 UTC, merged